In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

In [3]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers" , split= 'train')

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

ML-Arxiv-Papers.csv: reconstructing file:   0%|          |  0.00B /  147MB

ML-Arxiv-Papers.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [6]:
import pandas as pd

In [9]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [10]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [11]:
df=df[['title','abstract']]

In [12]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [13]:
df.shape

(117592, 2)

In [14]:
df=df.head(15000)

In [15]:
df.shape

(15000, 2)

In [16]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [17]:
df["paper_text"] = df["title"] + df["abstract"]

/tmp/ipykernel_695/3297733390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"] = df["title"] + df["abstract"]

In [18]:
# Save the processed DataFrame to a pickle file, so main.py can load it.
df.to_pickle('df.pkl')
print("DataFrame saved to df.pkl")

DataFrame saved to df.pkl

In [19]:
type(df["paper_text"])

pandas.core.series.Series

In [20]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations  The pro...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [21]:
print(df["paper_text"].iloc[0])

Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [22]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [23]:
# Uninstall torchcodec to resolve compatibility issues with PyTorch and sentence-transformers
!pip uninstall -y torchcodec

# --- IMPORTANT: After this cell runs, you MUST RESTART THE COLAB RUNTIME (Runtime > Restart runtime) ---
# --- Then, run all cells from the beginning of the notebook.                                         ---

from sentence_transformers import SentenceTransformer
print("SentenceTransformer imported successfully!")

# Update dynamic linker run-time bindings (kept from previous attempt if still relevant after restart)
!ldconfig

# Instantiate a model to further confirm it's working
try:
    model_test = SentenceTransformer("all-MiniLM-L6-v2")
    print("SentenceTransformer model loaded successfully!")
except Exception as e:
    print(f"Error loading SentenceTransformer model: {e}")

Found existing installation: torchcodec 0.11.0+cpu
Uninstalling torchcodec-0.11.0+cpu:
  Successfully uninstalled torchcodec-0.11.0+cpu
SentenceTransformer imported successfully!
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SentenceTransformer model loaded successfully!

In [24]:

model= SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [25]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [26]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [27]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_695/2190359946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
/tmp/ipykernel_695/2190359946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

In [28]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [29]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [30]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

In [31]:
sample_embedding=model.encode(df["paper_text"].head(5).to_list())

In [32]:
print(sample_embedding.shape)

(5, 384)

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
similarity=cosine_similarity(sample_embedding[0].reshape(1, -1),sample_embedding[0].reshape(1, -1))
print(similarity)

[[1.0000001]]

In [35]:
similarity=cosine_similarity(sample_embedding[0].reshape(1, -1),sample_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]

In [36]:
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1, -1),sample_embedding[1].reshape(1, -1))
  print(sim)

[[0.36625272]]
[[0.36625272]]
[[0.36625272]]
[[0.36625272]]

Generate full embedding

In [37]:
import os
import numpy as np

if os.path.exists(" paper_embeddings.npy"):
  print("Loading saved embeddings")

  embeddings=np.load(" paper_embeddings.npy")
else:
  print("Generating embeddings" )

  embeddings=model.encode(
      df["paper_text"].to_list(),

      batch_size=32,
      show_progress_bar=True

  )
  np.save("paper_embeddings.npy",embeddings)

  print("Embeddings saved successfully!") #embeddings =model.encode(
      #df["paper_text"].tolist()
      #batch_size=32,
      #show_progress_bar=True
      #)==============

Generating embeddings

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

Embeddings saved successfully!

In [38]:
print(embedding.shape)
print(type(embedding))

(384,)
<class 'numpy.ndarray'>

In [39]:
embedding.dtype

dtype('float32')

In [40]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 14.4 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

In [41]:
import faiss

In [42]:
faiss.normalize_L2(embedding.reshape(1, -1))

In [43]:
index=faiss.IndexFlatIP(384)

In [44]:
if os.path.exists("paper_faiss.index"):
  print("Loading existing index")
  index=faiss.read_index("paper_faiss.index")
else:
  print("Creating new FAISS index")
  faiss.normalize_L2(embeddings)
  index=faiss.IndexFlatIP(384)
  index.add(embeddings)
  faiss.write_index(index,"paper_faiss.index")
  print("FAISS index saved successfully!")

Creating new FAISS index
FAISS index saved successfully!

In [45]:
print(index.ntotal)

15000

In [46]:
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [47]:
faiss.normalize_L2(query_embedding)

In [48]:
D,I=index.search(query_embedding,5)
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [49]:
print(df.iloc[10466]["title"])

A Perspective on Deep Imaging

In [50]:
print(df.iloc[10466]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [52]:
print(df.iloc[11873]["title"])

Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

In [51]:
print(df.iloc[11873]["abstract"])

  The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).

In [53]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

In [54]:
D,I=search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [55]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Title",df.iloc[idx]['abstract'][:500])

In [56]:
search_paper("deep learning for medical image analysis")

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

In [57]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.13.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.23.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [58]:
from transformers import pipeline

# Initialize the text-generation pipeline with a suitable model like 'gpt2'
# We'll use this to approximate summarization since 'summarization' task was unavailable.
text_generator = pipeline("text-generation", model="gpt2")

print("Text generation pipeline initialized successfully!")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Text generation pipeline initialized successfully!

In [59]:
# Get the abstract to be summarized
abstract_to_summarize = df.iloc[10466]["abstract"]

# Use the text generator to create a summary. You might need to adjust parameters
# like max_length, num_return_sequences, and truncation based on desired output.
# Here, we'll try to generate a concise summary.
generated_summary = text_generator(
    abstract_to_summarize,
    max_length=150,  # Max length of the generated summary
    min_length=50,   # Min length of the generated summary
    num_return_sequences=1,
    truncation=True
)

print("Original Abstract (first 500 chars):")
print(abstract_to_summarize[:500])
print("\nGenerated Summary:")
print(generated_summary[0]['generated_text'])

[transformers] Passing `generation_config` together with generation-related arguments=({'num_return_sequences', 'min_length', 'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Original Abstract (first 500 chars):
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Generated Summary:
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

We need to be able to develop new models of image reconstruction, and to identify

the best model. It is essential that we develop a model that is robust, trustworthy,

valid, and scalable. The most important task is to develop the best

model that is able to predict the contour of a patient's heart, blood, and blood vessels. This

process will be a cornerstone for future imaging and patient care.

One of the main challenges in this field is to develop a model that is

valid, reliable, and scalable. The best model will have the

ability to predict the contour of a patient's heart, blood, and blood vessels. That

process will be a cornerstone for future imaging and patient care.

A key issue in machine learning is the

capacity of the model to reliably predict blood vessels. It is critical to

measure the contour of the heart at the heart, blood, and blood vessels.

For a model with a large number of blood vessels, such as a

cardiocerebral artery, it is important to use a model that is

efficient for such a test. A model with a small number of blood vessels,

In [60]:
generated_summary = text_generator(
    df.iloc[10466]["abstract"],
    max_length=120,
    min_length=40,
    num_return_sequences=1,
    truncation=True
)
print(generated_summary[0]['generated_text'])

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.
As a result of the great advances in information technology, machine learning has become the most
sophisticated of all systems in medicine. It has been widely recognized as a
new paradigm for imaging and is therefore becoming increasingly important for new
informatics and imaging techniques. This new paradigm is characterized by very sophisticated and
complex algorithms, and a broad range of techniques to support
machine learning.
Machine learning and image reconstruction are the three most important aspects of this new
disciplinary field of medicine. While the field is not yet fully understood (although
experts have been working on this topic for many years), the field is now
apparently gaining
increasing traction in other fields, including computer vision, image processing, and machine learning.
Machine learning has been used to solve many of the problems of imaging and
machine learning, and has been used in many imaging techniques, including image reconstruction, speech recognition,
memory, and speech recognition algorithms.
Machine learning has also in fact become a new field of research. In 2007,
machine learning was the most important domain of imaging
imaging and was used to design and develop imaging techniques. In 2010,
machine learning was the dominant approach for image reconstruction, although other
surgical techniques have also

In [61]:
type(generated_summary)

list

In [62]:
type (generated_summary[0])

dict

In [63]:
generated_summary[0] ["generated_text"]

'  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance in clinical and\npreclinical applications. To realize the full impact of machine learning on\nmedical imaging, major challenges must be addressed.\nAs a result of the great advances in information technology, machine learning has become the most\nsophisticated of all systems in medicine. It has been widely recognized as a\nnew paradigm for imaging and is therefore becoming increasingly important for new\ninformatics and imaging techniques. This new paradigm is characterized by very sophisticated and\ncomplex algorithms, and a broad range of techniques to support\nmachine learning.\nMachine learning and image reconstruction are the three most important aspects of this new\ndisciplinary field of medicine. While the field is not yet fully understood (although\nexperts have been working on this topic for many years), the field is now\napparently gaining\nincreasing traction in other fields, including computer vision, image processing, and machine learning.\nMachine learning has been used to solve many of the problems of imaging and\nmachine learning, and has been used in many imaging techniques, including image reconstruction, speech recognition,\nmemory, and speech recognition algorithms.\nMachine learning has also in fact become a new field of research. In 2007,\nmachine learning was the most important domain of imaging\nimaging and was used to design and develop imaging techniques. In 2010,\nmachine learning was the dominant approach for image reconstruction, although other\nsurgical techniques have also'

In [64]:
 for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Abstract (first 500 chars)",df.iloc[idx]['abstract'][:500])

    generated_summary = text_generator(df.iloc[idx]["abstract"], max_length=120, min_length=40, num_return_sequences=1, truncation=True)
    summary_text = generated_summary[0]["generated_text"]
    print("Generated Summary:", summary_text)
    print()

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Abstract (first 500 chars)   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

1. The first step in developing machine learning principles is to create a set of principles that can be applied

to a wide range of situations, from a large number of medical imaging tasks to the

large-scale training of a medical imaging and imaging team.

2. The human brain is the most important link between visual and auditory processing,

and is important for the development of new theories and techniques for machine learning.

3. The human brain is the most important link between the human cognitive system and the

human brain. It is the most important link between the human brain and the human brain. It is also the most important link

between cognitive processing, consciousness and the interaction between the two,

and it is the most important link between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and

the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two, and the interaction between the two,

Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract (first 500 chars)   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.
 of medical images as a training model to improve the
problems of image classification in patients with MS are justified?}

A simple, but potentially harmful, approach to image classification in MS patients is to train a trained neural network that

has a very good set of labeled images that are labeled to produce positive and negative images. This is an optimal

practice because it avoids the need for training a trained neural network that uses the same images

that are labeled for the same training. The two datasets are the same, and this

is the best way to model the network. We will then use the CNN to explore the

parameters of image classification and the generalization of the training process. We will explain

the training process in detail in the next section.

The training process

To begin with, we will be using an image classification algorithm that is very similar to

the one used by the CNN, but it is different in that it uses a new set of images. We will

explore this algorithm in the following section.

The CNN is a training network that uses a set of labeled images that are labeled to produce positive and

negative images. We first model a neural network that has

Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Abstract (first 500 chars)   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).
 set of
experiment data was obtained, we assumed that the model could be run on a large volume of

images and that the accuracy was not limited by the size or size of the images.

The main challenge is that the model is not sufficiently robust to reliably distinguish between images of different

types of brain matter. The model must also perform several other tasks, such as determining

where the data came from, and which structures were present in the image. In practice, this task is difficult

to perform, even for large volumes of images.

The main limitation is that the model is too broad for the task of

differentiating between images of different neurofibrillary tangles and

different neurofibrillary structures. In addition, the model has to be able to distinguish between the

different types of images in the human brain. Thus, the model is not

a good generalisation for the diagnosis of neurofibrillary

tissue problems and can't be generalized to those cases in which there

are multiple sets of neurofibrillary structures.

We had a total of 18 participants who were randomly assigned to

one of four groups. The first group was a control group

Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Abstract (first 500 chars)   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.
 provide a good approximation of
the neural network's response to the information presented.

In the present work, we introduce a new approach, which combines the previous experience of

deep-learning and deep-machine learning and provides an approach to better understand the neural network

and the underlying features of the system.

Our approach is based on the idea that neural network architectures are inherently

different than deep-learning models. The main goal of this work is to present an alternative approach

based on the experience of deep-learning models.

In particular, the following elements are used:

(1) The neural network is in a general state of being

connected to an input vector or input vector with a given signal and direction

(2) The neural network is in a general state of being connected to an input vector

with a given signal and direction (3) A signal and direction can be given for each

input vector or input vector with a given signal and direction (4) A vector of the given signal and direction can be

composed of a set of different inputs with different outputs

(5) The neural network is in a general state of being connected to an input

vector

Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Abstract (first 500 chars)   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar
Generated Summary:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN architecture and classification accuracy for the
original images of lung nodules. In order to understand the features of lung
nodules, we further construct new datasets, based on the combination of
artificial geometric nodules and some transformations of the original images,
as well as a stochastic nodule shape model. It is found that simplistic
geometric nodules cannot capture the important features of lung nodules.
 (TNCs) in a large image file (500 × 1000 × 1000 cm) using the method of

S. G. M. Eriksson, L. J. I. C. P. Weitzman, J. K. H. Hejtz, J. F. F. van der Maan,

V. A. G. L. van der Maan, M. B. S. van Rooijen, C. E. van der Maan,

V. A. G. L. van der Maan, M. B. S. van der Maan,

V. A. G. L. van der Maan, M. B. S. van der Maan, P. W. G.

Eriksson, J. L. van der Maan, V. A. G. L., J. J. M. van der Maan, C. E. van der Maan, J. J.

C. Eriksson, A. Eriksson, M. B. van der Maan, J. A. van der Maan, J. A. van der Maan,

V. A

In [65]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Title",df.iloc[idx]['abstract'][:500])
    print()
    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40,do_sample=False)
    print(summary)
    print(summary[0] ["summary_text"] )
    print()

In [66]:
!pip install keybert==0.8.5

Collecting keybert==0.8.5
  Downloading keybert-0.8.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert==0.8.5) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.0.4)
Downloading keybert-0.8.5-py3-none-any.whl (37 kB)
Installing collected packages: keybert
Successfully installed keybert-0.8.5

In [67]:
from keybert import KeyBERT

In [68]:
kw_model = KeyBERT(model)

In [69]:
type(kw_model)#model= SentenceTransformer("all-MiniLM-L6-v2")

keybert._model.KeyBERT

In [70]:
text=df.iloc[10466]["abstract"]
keywords=kw_model.extract_keywords(text)

In [71]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [72]:
print(type(keywords))

<class 'list'>

In [73]:
print(type(keywords[0]))

<class 'tuple'>

In [74]:
kw_model.extract_keywords(text,keyphrase_ngram_range=(1,1),stop_words="english")

[('imaging', 0.4528),
 ('tomographic', 0.4488),
 ('reconstruction', 0.3623),
 ('deep', 0.3003),
 ('learning', 0.2622)]

In [75]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [76]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Title",df.iloc[idx]['abstract'][:500])
    print()
    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40,do_sample=False)
    print(summary)
    print(summary[0] ["summary_text"] )
    print()
    kw_model.extract_keywords(text,keyphrase_ngram_range=(1,1),stop_words="english")
    print(keywords)
    for k,s in keywords:
      print(K)

In [77]:
!pip install fastapi uvicorn nest-asyncio

Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (0.139.0)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (0.51.0)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (1.3.1)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (2.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.0.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (8.4.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (2.46.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi) (4.14.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.18)

In [78]:
# Save the processed DataFrame to a pickle file for FastAPI to load
df.to_pickle('df.pkl')

In [79]:
%%writefile main.py
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import nest_asyncio
import pandas as pd
import numpy as np
import faiss
import os
from sentence_transformers import SentenceTransformer
from transformers import pipeline

# --- Load NLP resources ---

df = pd.DataFrame() # Initialize empty DataFrame
try:
    if os.path.exists("df.pkl"):
        df = pd.read_pickle("df.pkl")
        if "paper_text" not in df.columns:
            df["paper_text"] = df["title"] + df["abstract"]
            df["paper_text"] = df["paper_text"].str.replace("\\n", " ", regex=False)
            df["paper_text"] = df["paper_text"].str.strip()
except Exception as e:
    print(f"Error loading DataFrame: {e}")

model = None
try:
    model = SentenceTransformer("all-MiniLM-L6-v2")
except Exception as e:
    print(f"Error loading SentenceTransformer model: {e}")

# Initialize the text-generation pipeline as a workaround for summarization
text_generator = None
try:
    text_generator = pipeline("text-generation", model="gpt2")
    print("Text generation pipeline initialized successfully in FastAPI!")
except Exception as e:
    print(f"Error loading text-generation pipeline: {e}")

index = None
try:
    if os.path.exists("paper_faiss.index"):
        index = faiss.read_index("paper_faiss.index")
except Exception as e:
    print(f"Error loading FAISS index: {e}")

app = FastAPI()

class QueryRequest(BaseModel):
    query: str
    k: int = 5

@app.get("/shard")
async def root():
    return {"message": "Hello from FastAPI!"}

@app.post("/search_and_summarize/")
async def run_search_and_summarize(request: QueryRequest):
    if model is None or text_generator is None or index is None or df.empty:
        raise HTTPException(status_code=503, detail="NLP resources not loaded. Server is not ready.")

    results = []
    try:
        query_embedding = model.encode([request.query])
        faiss.normalize_L2(query_embedding)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error encoding query: {e}")

    try:
        D, I = index.search(query_embedding, request.k)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error performing FAISS search: {e}")

    for score, idx in zip(D[0], I[0]):
        try:
            if idx >= len(df):
                continue

            abstract_text = df.iloc[idx]['abstract']

            summary_text = "Summarizer not available."
            if text_generator:
                # Use text_generator for summarization
                generated_summary = text_generator(
                    abstract_text,
                    max_length=120,
                    min_length=40,
                    num_return_sequences=1,
                    truncation=True
                )
                summary_text = generated_summary[0]["generated_text"]

            results.append({
                "score": float(score),
                "title": df.iloc[idx]['title'],
                "abstract_snippet": abstract_text[:500] + "...",
                "summary_text": summary_text,
            })
        except IndexError:
            pass
        except Exception as e:
            print(f"Error processing result for index {idx}: {e}")
            continue

    return {"query": request.query, "results": results}

Writing main.py

In [80]:
import uvicorn
import nest_asyncio
import threading
import time
from main import app

nest_asyncio.apply()

def run_fastapi_threaded():
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="error", reload=False)

fastapi_thread = threading.Thread(target=run_fastapi_threaded)
fastapi_thread.daemon = True
fastapi_thread.start()
time.sleep(5)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Text generation pipeline initialized successfully in FastAPI!

In [81]:
import requests

response = requests.get("http://localhost:8000/shard")
print(response.json())

query_data = {"query": "deep learning in medical imaging", "k": 3}
response = requests.post("http://localhost:8000/search_and_summarize/", json=query_data)
print(response.json())

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'message': 'Hello from FastAPI!'}

[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'query': 'deep learning in medical imaging', 'results': [{'score': 0.7354985475540161, 'title': 'A Perspective on Deep Imaging', 'abstract_snippet': '  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance...', 'summary_text': "  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance in clinical and\npreclinical applications. To realize the full impact of machine learning on\nmedical imaging, major challenges must be addressed.\n\nAn important aspect of this direction is the development of new imaging and deep\n\nlearning methods for image reconstruction. The latter is the most important of these, because it provides\n\na more comprehensive picture of the individual patient. It is also the most\n\npreferred method for image reconstruction that is currently being developed.\n\nMolecular Image Reconstruction\n\nA technique that is used to reconstruct the tissue's structure and function\n\nfor a given patient is called molecular image reconstruction. The process is\n\nalso referred to as a molecular image reconstruction. A technique is called molecular\n\nimage reconstruction because it is the first step in the process of reconstructing\n\nthe tissue's structure after the patient was born. An important aspect of\n\nmolecular image reconstruction is that it is the starting point for a\n\nhigh resolution image of the tissue. This is because the reconstruction is\n\ntypically done at the end of the fetal period, and is performed by\n\na machine learning system that is a combination of techniques developed and applied by\n\nspecialists in the field. A high resolution reconstruction of the tissue, however,\n\ndoes not require a long time to complete, because it is done in a slow\n\nmotion process, whereas a"}, {'score': 0.6881735920906067, 'title': 'Classification of MRI data using Deep Learning and Gaussian\n  Process-based Model Selection', 'abstract_snippet': '  The classification of MRI images according to the anatomical field of view is\na necessary task to solve when faced with the increasing quantity of medical\nimages. In parallel, advances in deep learning makes it a suitable tool for\ncomputer vision problems. Using a common architecture (such as AlexNet)\nprovides quite good results, but not sufficient for clinical use. Improving the\nmodel is not an easy task, due to the large number of hyper-parameters\ngoverning both the architecture and the trai...', 'summary_text': '  The classification of MRI images according to the anatomical field of view is\na necessary task to solve when faced with the increasing quantity of medical\nimages. In parallel, advances in deep learning makes it a suitable tool for\ncomputer vision problems. Using a common architecture (such as AlexNet)\nprovides quite good results, but not sufficient for clinical use. Improving the\nmodel is not an easy task, due to the large number of hyper-parameters\ngoverning both the architecture and the training of the network, and to the\nlimited understanding of their relevance. Since an exhaustive search is not\ntractable, we propose to optimize the network first by random search, and then\nby an adaptive search based on Gaussian Processes and Probability of\nImprovement. Applying this method on a large and varied MRI dataset, we show a\nsubstantial improvement between the baseline network and the final one (up to\n20\\% for the most difficult classes).\n description of the\n`complex structure of the image (in a series of three dimensions) is required,\n\nit is necessary to know the architecture of the network. This is achieved by\n\nexploring the architecture of the network, the basic parameters of the network, and\n\nthe model parameters. The model parameters are available as a module name in the\n\nmodel-specification of the model.\n\nIn addition, it is necessary to learn the model parameters.\n\nThe model parameters are available as a module name in the model-specification of the model. The model parameters are available as a module name in the model-specification of the model.\n\nThe model parameters are available as a module name in the model-specification of the model.\n\nThe model parameters are available as a module name in the model-specification of the model.\n\nThe model parameters are available as a module name in the model-specification of the model.\n\nThe model parameters are available as module name in the model-specification of the model.\n\nThe model parameters are available as module name in the model-specification of the model.\n\nThe model parameters are available as module name in the model-specification'}, {'score': 0.6532081961631775, 'title': 'Convolutional Neural Networks for Medical Image Analysis: Full Training\n  or Fine Tuning?', 'abstract_snippet': '  Training a deep convolutional neural network (CNN) from scratch is difficult\nbecause it requires a large amount of labeled training data and a great deal of\nexpertise to ensure proper convergence. A promising alternative is to fine-tune\na CNN that has been pre-trained using, for instance, a large set of labeled\nnatural images. However, the substantial differences between natural and\nmedical images may advise against such knowledge transfer. In this paper, we\nseek to answer the following centra...', 'summary_text': "  Training a deep convolutional neural network (CNN) from scratch is difficult\nbecause it requires a large amount of labeled training data and a great deal of\nexpertise to ensure proper convergence. A promising alternative is to fine-tune\na CNN that has been pre-trained using, for instance, a large set of labeled\nnatural images. However, the substantial differences between natural and\nmedical images may advise against such knowledge transfer. In this paper, we\nseek to answer the following central question in the context of medical image\nanalysis: \\emph{Can the use of pre-trained deep CNNs with sufficient\nfine-tuning eliminate the need for training a deep CNN from scratch?} To\naddress this question, we considered 4 distinct medical imaging applications in\n3 specialties (radiology, cardiology, and gastroenterology) involving\nclassification, detection, and segmentation from 3 different imaging\nmodalities, and investigated how the performance of deep CNNs trained from\nscratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.\nOur experiments consistently demonstrated that (1) the use of a pre-trained CNN\nwith adequate fine-tuning outperformed or, in the worst case, performed as well\nas a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size\nof training sets than CNNs trained from scratch; (3) neither shallow tuning nor\ndeep tuning was the optimal choice for a particular application; and (4) our\nlayer-wise fine-tuning scheme could offer a practical way to reach the best\nperformance for the application at hand based on the amount of available data.\n of a CNN as a training tool for medicine be justified?}\n\nCan the use of a CNN be justified? -The answer to this question depends on the underlying design of the CNN, and the\n\nnature and potential risks involved in the use of a CNN, including the potential\n\ndangerous effect of having a CNN trained on a patient's brain, such as for\n\nsmoking or for trauma. Given the complexity of the questions and the\n\nsimplicity of the data, the current answer is ``no''.\n\nTo begin with, the CNN is not a reliable, well-tested, well-trained CNN. In\n\na large, well-trained CNN, we would be unable to verify the accuracy of an image\n\nof an individual patient. In contrast, if we trained a CNN on a patient's\n\nbrain, we would be able to detect the contralateral effects of smoking,\n\nfor example, and the contralateral effects of trauma. In this case, we would be\n\nin a position to test the CNN on the patient's brain while it was being trained.\n\nTo test this, we would be trained to have a CNN trained on a CNN. This would\n\nbe a good"}]}

In [82]:
!pip install langchain - community langchain_core

ERROR: Invalid requirement: '-': Expected package name at the start of dependency specifier
    -
    ^

In [83]:
from langchain_core.tools import tool

In [84]:
@tool
def search_paper(query:str)->str:
  "Search research paper from the faiss database and return the most relevant result"

In [85]:
!pip install langchain-community langchain-core langchain-huggingface
from langchain_huggingface import HuggingFacePipeline

Collecting langchain-community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (1.4.9)
Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.10.2)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.0.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (2.13.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.17.0)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.23.0)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.22.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.8.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 22.3 MB/s eta 0:00:00
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 14.7 MB/s eta 0:00:00
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 2.2 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 2.8 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: requests, httpx-sse, pydantic-settings, langchain-text-splitters, langchain-huggingface, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
Successfully installed httpx-sse-0.4.3 langchain-classic-1.0.8 langchain-community-0.4.2 langchain-huggingface-1.2.2 langchain-text-splitters-1.1.2 pydantic-settings-2.14.2 requests-2.34.2

In [88]:
llm=HuggingFacePipeline(pipeline=text_generator)

In [90]:
llm

HuggingFacePipeline(metadata={'lc_versions': {'langchain-core': '1.4.9', 'langchain': '1.3.13'}}, pipeline=TextGenerationPipeline: {'model': 'GPT2LMHeadModel', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text', 'output_modalities': ('text',)}, model_id='gpt2')

In [91]:
llm.invoke("Although depressive symptoms (DS) and physical activity (PA) have each been associated with social frailty (SF), their combined associations remain unclear. This study examined the associations of DS and objectively measured PA with SF in community-dwelling older adults. This cross-sectional study included 147 adults aged ≥ 65 years. DS were assessed using the Japanese version of the 15-item Geriatric Depression Scale, and PA was measured objectively via accelerometer-based daily step counts, classified as < 4,000 or ≥ 4,000 steps/day. SF was evaluated using the five-item criteria proposed by Makizako et al. A two-way analysis of covariance was performed with DS (yes/no) and step count (≥ 4,000/<4,000) as independent variables and the total number of positive SF components (0–5) as the dependent variable, adjusting for relevant covariates. Participants with DS and those walking < 4,000 steps/day had significantly higher SF scores (both P < 0.001). A significant interaction between DS and step count was also observed (P = 0.006); however, this finding should be interpreted cautiously because the subgroup with both DS and low step counts was small (n = 6). These findings suggest that both DS and low PA are associated with higher SF scores, while the potential combined association of these factors warrants further investigation in la")

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

'Although depressive symptoms (DS) and physical activity (PA) have each been associated with social frailty (SF), their combined associations remain unclear. This study examined the associations of DS and objectively measured PA with SF in community-dwelling older adults. This cross-sectional study included 147 adults aged\u2009≥\u200965 years. DS were assessed using the Japanese version of the 15-item Geriatric Depression Scale, and PA was measured objectively via accelerometer-based daily step counts, classified as <\u20094,000 or ≥\u20094,000 steps/day. SF was evaluated using the five-item criteria proposed by Makizako et al. A two-way analysis of covariance was performed with DS (yes/no) and step count (≥\u20094,000/<4,000) as independent variables and the total number of positive SF components (0–5) as the dependent variable, adjusting for relevant covariates. Participants with DS and those walking\u2009<\u20094,000 steps/day had significantly higher SF scores (both P\u2009<\u20090.001). A significant interaction between DS and step count was also observed (P\u2009=\u20090.006); however, this finding should be interpreted cautiously because the subgroup with both DS and low step counts was small (n\u2009=\u20096). These findings suggest that both DS and low PA are associated with higher SF scores, while the potential combined association of these factors warrants further investigation in lauren et al. (2015).\n\nWe hypothesized that low PA and high SF would be associated and possibly associated with higher SF scores. This may be related to the fact that both DS and low PA are associated with higher SF scores, and low PA may be associated with lower SF scores. In a previous study on the effects of physical activity on SF (Piper et al., 2002) we found that low PA and low SF were associated with higher SF scores, but the association was not significant. This finding warrants further investigation into the association of DS and low PA with SF and its relation to SF.\n\nTo our knowledge, the only independent variables that were significant were physical activity, although the association was not significant because of the small sample size. In a similar meta-analysis (Sommer et al., 2004) we found that the association between DS and low PA and SF was not significant because of the small sample size (P=0.07). In addition, the association between DS and low PA was not significant because of the small sample size (P=0.17).\n\nTo our knowledge, the only independent variables that were significant were physical activity, although the association was not significant because of the small sample size. In a previous meta-'

In [92]:
response

In [89]:
print(type(response))

<class 'requests.models.Response'>

In [93]:
!pip install -U langchain-groq

Collecting langchain-groq
  Downloading langchain_groq-1.1.3-py3-none-any.whl.metadata (2.9 kB)
Collecting groq<1.0.0,>=0.30.0 (from langchain-groq)
  Downloading groq-0.37.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-groq) (1.4.9)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (2.13.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.10.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.17.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq<1.0.0,>=0.30.0->langchain-groq) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.34.2)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.8.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.5.0)
Downloading langchain_groq-1.1.3-py3-none-any.whl (20 kB)
Downloading groq-0.37.1-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 4.6 MB/s eta 0:00:00
Installing collected packages: groq, langchain-groq
Successfully installed groq-0.37.1 langchain-groq-1.1.3

In [94]:
from langchain_groq import ChatGroq

In [95]:
from google.colab import userdata
userdata.get('researchpaperassistantproject')

'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'

In [96]:
api_key = userdata.get("researchpaperassistantproject")

In [97]:
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    api_key=api_key,
    temperature=0
)

In [98]:
response = llm.invoke("Hello, who are you?")

In [99]:
response.content

"I'm an artificial intelligence model known as a large language model (LLM) or conversational AI. I'm a computer program designed to understand and respond to human language in a way that's natural and helpful.\n\nI don't have a personal identity or emotions like humans do, but I'm here to assist you with any questions, topics, or tasks you'd like to discuss. I can provide information, answer questions, generate text, and even engage in conversation.\n\nI'm constantly learning and improving my responses based on the data and interactions I receive, so feel free to ask me anything and I'll do my best to help!"

In [100]:
from langchain_core.tools import tool

In [101]:

@tool
def search_and_summarize(query: str, k: int = 5) -> str:
    """
    Search research papers from the FAISS database,
    retrieve the top-k most similar papers,
    summarize each paper using BART,
    and return the results.
    """


    query_embedding = model.encode([query])


    faiss.normalize_L2(query_embedding)


    D, I = index.search(query_embedding, k)


    result = ""

    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):

        paper = df.iloc[idx]


        summary = summarizer(
            paper["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )[0]["summary_text"]


        result += f"Rank: {rank}\n"
        result += f"Similarity Score: {round(float(score),4)}\n"
        result += f"Title: {paper['title']}\n\n"


        result += paper["abstract"] + "\n\n"


        result += summary + "\n\n"

    return result

In [102]:
tools = [search_and_summarize]

In [103]:
from langchain.agents import create_agent

In [104]:
agent = create_agent(
    model=llm,
    tools=tools
)

In [112]:
response = agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": "Find the top 3 research papers on Vision Transformer."
            }
        ]
    }
)

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'min_length', 'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [113]:
response

{'messages': [HumanMessage(content='Find the top 3 research papers on Vision Transformer.', additional_kwargs={}, response_metadata={}, id='f9701a45-3150-42e7-9ada-82f909797877'),
  AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'gmbq80h9s', 'function': {'arguments': '{"k":3,"query":"Vision Transformer"}', 'name': 'search_and_summarize'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 376, 'total_tokens': 399, 'completion_time': 0.033790214, 'completion_tokens_details': None, 'prompt_time': 0.026584103, 'prompt_tokens_details': None, 'queue_time': 0.006247971, 'total_time': 0.060374317}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f78b6-8b2f-7920-aa16-997b85ec9d2e-0', tool_calls=[{'name': 'search_and_summarize', 'args': {'k': 3, 'query': 'Vision Transformer'}, 'id': 'gmbq80h9s', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 376, 'output_tokens': 23, 'total_tokens': 399}),
  ToolMessage(content='[{"rank": 1, "similarity": 0.4415, "title": "Dense Transformer Networks", "abstract": "  The key idea of current deep learning methods for dense prediction is to\\napply a model on a regular patch centered on each pixel to make pixel-wise\\npredictions. These methods are limited in the sense that the patches are\\ndetermined by network architecture instead of learned from data. In this work,\\nwe propose the dense transformer networks, which can learn the shapes and sizes\\nof patches from data. The dense transformer networks employ an encoder-decoder\\narchitecture, and a pair of dense transformer modules are inserted into each of\\nthe encoder and decoder paths. The novelty of this work is that we provide\\ntechnical solutions for learning the shapes and sizes of patches from data and\\nefficiently restoring the spatial correspondence required for dense prediction.\\nThe proposed dense transformer modules are differentiable, thus the entire\\nnetwork can be trained. We apply the proposed networks on natural and\\nbiological image segmentation tasks and show superior performance is achieved\\nin comparison to baseline methods.\\n", "summary": "  The key idea of current deep learning methods for dense prediction is to\\napply a model on a regular patch centered on each pixel to make pixel-wise\\npredictions. These methods are limited in the sense that the patches are\\ndetermined by network architecture instead of learned from data. In this work,\\nwe propose the dense transformer networks, which can learn the shapes and sizes\\nof patches from data. The dense transformer networks employ an encoder-decoder\\narchitecture, and a pair of dense transformer modules are inserted into each of\\nthe encoder and decoder paths. The novelty of this work is that we provide\\ntechnical solutions for learning the shapes and sizes of patches from data and\\nefficiently restoring the spatial correspondence required for dense prediction.\\nThe proposed dense transformer modules are differentiable, thus the entire\\nnetwork can be trained. We apply the proposed networks on natural and\\nbiological image segmentation tasks and show superior performance is achieved\\nin comparison to baseline methods.\\n The encoder and decoder paths are then connected to the\\ncomputation of the patches. The encoder and decoder paths are then connected to the\\ncomputation of the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches."}, {"rank": 2, "similarity": 0.4169, "title": "Inverse Compositional Spatial Transformer Networks", "abstract": "  In this paper, we establish a theoretical connection between the classical\\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\\nNetworks (STNs). STNs are of interest to the vision and learning communities\\ndue to their natural ability to combine alignment and classification within the\\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\\nthan conventional STNs with less model capacity; in particular, we show\\nsuperior performance in pure image alignment tasks as well as joint\\nalignment/classification problems on real-world problems.\\n", "summary": "  In this paper, we establish a theoretical connection between the classical\\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\\nNetworks (STNs). STNs are of interest to the vision and learning communities\\ndue to their natural ability to combine alignment and classification within the\\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\\nthan conventional STNs with less model capacity; in particular, we show\\nsuperior performance in pure image alignment tasks as well as joint\\nalignment/classification problems on real-world problems.\\n LK algorithms, and that they can be used to perform\\nthe same task in a much more efficient manner. We also show that IC-STNs can be used to perform\\nthe same task in a much more efficient manner.\\n\\nIn this paper, we establish a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs). STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework. Inspired by thein the LK algorithm, we presentin the LK algorithm. We demonstrate that IC-STNs can achieve better performancethan conventional LK algorithms, and that they can be used to perform the same task in a much more efficient manner. We also show that IC-STNs can be used to perform the same task in a much more efficient manner.\\n\\nIn this paper, we establish a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs). STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework. Inspired by thein"}, {"rank": 3, "similarity": 0.4107, "title": "gvnn: Neural Network Library for Geometric Computer Vision", "abstract": "  We introduce gvnn, a neural network library in Torch aimed towards bridging\\nthe gap between classic geometric computer vision and deep learning. Inspired\\nby the recent success of Spatial Transformer Networks, we propose several new\\nlayers which are often used as parametric transformations on the data in\\ngeometric computer vision. These layers can be inserted within a neural network\\nmuch in the spirit of the original spatial transformers and allow\\nbackpropagation to enable end-to-end learning of a network involving any domain\\nknowledge in geometric computer vision. This opens up applications in learning\\ninvariance to 3D geometric transformation for place recognition, end-to-end\\nvisual odometry, depth estimation and unsupervised learning through warping\\nwith a parametric transformation for image reconstruction error.\\n", "summary": "  We introduce gvnn, a neural network library in Torch aimed towards bridging\\nthe gap between classic geometric computer vision and deep learning. Inspired\\nby the recent success of Spatial Transformer Networks, we propose several new\\nlayers which are often used as parametric transformations on the data in\\ngeometric computer vision. These layers can be inserted within a neural network\\nmuch in the spirit of the original spatial transformers and allow\\nbackpropagation to enable end-to-end learning of a network involving any domain\\nknowledge in geometric computer vision. This opens up applications in learning\\ninvariance to 3D geometric transformation for place recognition, end-to-end\\nvisual odometry, depth estimation and unsupervised learning through warping\\nwith a parametric transformation for image reconstruction error.\\n the field of\\nsparse and sparse data structures, and in the field of deep learning.\\n\\nThe goal of this paper is to provide a framework for building a neural network\\n\\nthat can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a"}]', name='search_and_summarize', id='5cbb25d0-8eff-44f9-a7c7-b277fece27f6', tool_call_id='gmbq80h9s'),
  AIMessage(content='Based on the search results, the top 3 research papers on Vision Transformer are:\n\n1. "Dense Transformer Networks" - This paper proposes a new architecture for dense prediction tasks, which can learn the shapes and sizes of patches from data. The dense transformer networks employ an encoder-decoder architecture, and a pair of dense transformer modules are inserted into each of the encoder and decoder paths.\n2. "Inverse Compositional Spatial Transformer Networks" - This paper establishes a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer Networks (STNs). The authors present Inverse Compositional Spatial Transformer Networks (IC-STNs), which can achieve better performance than conventional STNs with less model capacity.\n3. "gvnn: Neural Network Library for Geometric Computer Vision" - This paper introduces a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. The authors propose several new layers which are often used as parametric transformations on the data in geometric computer vision.\n\nThese papers are all related to the topic of Vision Transformer and have been identified as the top 3 results based on their similarity to the query "Vision Transformer".', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 244, 'prompt_tokens': 2293, 'total_tokens': 2537, 'completion_time': 0.322274181, 'completion_tokens_details': None, 'prompt_time': 0.182083739, 'prompt_tokens_details': None, 'queue_time': 0.010112415, 'total_time': 0.50435792}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f78b7-509e-7ce1-b1b4-8cc79e0e98a2-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 2293, 'output_tokens': 244, 'total_tokens': 2537})]}

In [114]:
print(type(response))

<class 'dict'>

In [115]:
print(response.keys())

dict_keys(['messages'])

In [116]:
len(response["messages"])

4

In [117]:
response["messages"][0]

HumanMessage(content='Find the top 3 research papers on Vision Transformer.', additional_kwargs={}, response_metadata={}, id='f9701a45-3150-42e7-9ada-82f909797877')

In [118]:
response["messages"][1]

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'gmbq80h9s', 'function': {'arguments': '{"k":3,"query":"Vision Transformer"}', 'name': 'search_and_summarize'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 376, 'total_tokens': 399, 'completion_time': 0.033790214, 'completion_tokens_details': None, 'prompt_time': 0.026584103, 'prompt_tokens_details': None, 'queue_time': 0.006247971, 'total_time': 0.060374317}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f78b6-8b2f-7920-aa16-997b85ec9d2e-0', tool_calls=[{'name': 'search_and_summarize', 'args': {'k': 3, 'query': 'Vision Transformer'}, 'id': 'gmbq80h9s', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 376, 'output_tokens': 23, 'total_tokens': 399})

In [119]:
response["messages"][2]

ToolMessage(content='[{"rank": 1, "similarity": 0.4415, "title": "Dense Transformer Networks", "abstract": "  The key idea of current deep learning methods for dense prediction is to\\napply a model on a regular patch centered on each pixel to make pixel-wise\\npredictions. These methods are limited in the sense that the patches are\\ndetermined by network architecture instead of learned from data. In this work,\\nwe propose the dense transformer networks, which can learn the shapes and sizes\\nof patches from data. The dense transformer networks employ an encoder-decoder\\narchitecture, and a pair of dense transformer modules are inserted into each of\\nthe encoder and decoder paths. The novelty of this work is that we provide\\ntechnical solutions for learning the shapes and sizes of patches from data and\\nefficiently restoring the spatial correspondence required for dense prediction.\\nThe proposed dense transformer modules are differentiable, thus the entire\\nnetwork can be trained. We apply the proposed networks on natural and\\nbiological image segmentation tasks and show superior performance is achieved\\nin comparison to baseline methods.\\n", "summary": "  The key idea of current deep learning methods for dense prediction is to\\napply a model on a regular patch centered on each pixel to make pixel-wise\\npredictions. These methods are limited in the sense that the patches are\\ndetermined by network architecture instead of learned from data. In this work,\\nwe propose the dense transformer networks, which can learn the shapes and sizes\\nof patches from data. The dense transformer networks employ an encoder-decoder\\narchitecture, and a pair of dense transformer modules are inserted into each of\\nthe encoder and decoder paths. The novelty of this work is that we provide\\ntechnical solutions for learning the shapes and sizes of patches from data and\\nefficiently restoring the spatial correspondence required for dense prediction.\\nThe proposed dense transformer modules are differentiable, thus the entire\\nnetwork can be trained. We apply the proposed networks on natural and\\nbiological image segmentation tasks and show superior performance is achieved\\nin comparison to baseline methods.\\n The encoder and decoder paths are then connected to the\\ncomputation of the patches. The encoder and decoder paths are then connected to the\\ncomputation of the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches. The patches are then connected to the patches."}, {"rank": 2, "similarity": 0.4169, "title": "Inverse Compositional Spatial Transformer Networks", "abstract": "  In this paper, we establish a theoretical connection between the classical\\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\\nNetworks (STNs). STNs are of interest to the vision and learning communities\\ndue to their natural ability to combine alignment and classification within the\\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\\nthan conventional STNs with less model capacity; in particular, we show\\nsuperior performance in pure image alignment tasks as well as joint\\nalignment/classification problems on real-world problems.\\n", "summary": "  In this paper, we establish a theoretical connection between the classical\\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\\nNetworks (STNs). STNs are of interest to the vision and learning communities\\ndue to their natural ability to combine alignment and classification within the\\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\\nthan conventional STNs with less model capacity; in particular, we show\\nsuperior performance in pure image alignment tasks as well as joint\\nalignment/classification problems on real-world problems.\\n LK algorithms, and that they can be used to perform\\nthe same task in a much more efficient manner. We also show that IC-STNs can be used to perform\\nthe same task in a much more efficient manner.\\n\\nIn this paper, we establish a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs). STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework. Inspired by thein the LK algorithm, we presentin the LK algorithm. We demonstrate that IC-STNs can achieve better performancethan conventional LK algorithms, and that they can be used to perform the same task in a much more efficient manner. We also show that IC-STNs can be used to perform the same task in a much more efficient manner.\\n\\nIn this paper, we establish a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs). STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework. Inspired by thein"}, {"rank": 3, "similarity": 0.4107, "title": "gvnn: Neural Network Library for Geometric Computer Vision", "abstract": "  We introduce gvnn, a neural network library in Torch aimed towards bridging\\nthe gap between classic geometric computer vision and deep learning. Inspired\\nby the recent success of Spatial Transformer Networks, we propose several new\\nlayers which are often used as parametric transformations on the data in\\ngeometric computer vision. These layers can be inserted within a neural network\\nmuch in the spirit of the original spatial transformers and allow\\nbackpropagation to enable end-to-end learning of a network involving any domain\\nknowledge in geometric computer vision. This opens up applications in learning\\ninvariance to 3D geometric transformation for place recognition, end-to-end\\nvisual odometry, depth estimation and unsupervised learning through warping\\nwith a parametric transformation for image reconstruction error.\\n", "summary": "  We introduce gvnn, a neural network library in Torch aimed towards bridging\\nthe gap between classic geometric computer vision and deep learning. Inspired\\nby the recent success of Spatial Transformer Networks, we propose several new\\nlayers which are often used as parametric transformations on the data in\\ngeometric computer vision. These layers can be inserted within a neural network\\nmuch in the spirit of the original spatial transformers and allow\\nbackpropagation to enable end-to-end learning of a network involving any domain\\nknowledge in geometric computer vision. This opens up applications in learning\\ninvariance to 3D geometric transformation for place recognition, end-to-end\\nvisual odometry, depth estimation and unsupervised learning through warping\\nwith a parametric transformation for image reconstruction error.\\n the field of\\nsparse and sparse data structures, and in the field of deep learning.\\n\\nThe goal of this paper is to provide a framework for building a neural network\\n\\nthat can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a framework for building a neural network that can be used to build a deep learning model of a data set.\\n\\nThe goal of this paper is to provide a"}]', name='search_and_summarize', id='5cbb25d0-8eff-44f9-a7c7-b277fece27f6', tool_call_id='gmbq80h9s')

In [120]:
response["messages"][3]

AIMessage(content='Based on the search results, the top 3 research papers on Vision Transformer are:\n\n1. "Dense Transformer Networks" - This paper proposes a new architecture for dense prediction tasks, which can learn the shapes and sizes of patches from data. The dense transformer networks employ an encoder-decoder architecture, and a pair of dense transformer modules are inserted into each of the encoder and decoder paths.\n2. "Inverse Compositional Spatial Transformer Networks" - This paper establishes a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer Networks (STNs). The authors present Inverse Compositional Spatial Transformer Networks (IC-STNs), which can achieve better performance than conventional STNs with less model capacity.\n3. "gvnn: Neural Network Library for Geometric Computer Vision" - This paper introduces a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. The authors propose several new layers which are often used as parametric transformations on the data in geometric computer vision.\n\nThese papers are all related to the topic of Vision Transformer and have been identified as the top 3 results based on their similarity to the query "Vision Transformer".', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 244, 'prompt_tokens': 2293, 'total_tokens': 2537, 'completion_time': 0.322274181, 'completion_tokens_details': None, 'prompt_time': 0.182083739, 'prompt_tokens_details': None, 'queue_time': 0.010112415, 'total_time': 0.50435792}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f78b7-509e-7ce1-b1b4-8cc79e0e98a2-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 2293, 'output_tokens': 244, 'total_tokens': 2537})

In [121]:

@tool
def search_and_summarize(query: str, k: int = 5):
    """
    Search research papers from the FAISS database,
    retrieve the top-k most similar papers,
    summarize each paper using BART,
    and return the results as structured data.
    """

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)


    D, I = index.search(query_embedding, k)

    papers = []

    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):

        paper = df.iloc[idx]

        summary = text_generator(
            paper["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )[0]["generated_text"]


        paper_data = {
            "rank": rank,
            "similarity": round(float(score), 4),
            "title": paper["title"],
            "abstract": paper["abstract"],
            "summary": summary
        }

        papers.append(paper_data)

    return papers

In [122]:

@tool
def extract_keywords(text: str, top_n: int = 5) -> str:
    """
    Extract the most important keywords from the given text
    using the KeyBERT model.
    """


    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 2),
        stop_words="english",
        top_n=top_n
    )

    result = "Top Keywords:\n\n"

    for rank, (keyword, score) in enumerate(keywords, start=1):

        result += (
            f"{rank}. {keyword} "
            f"(Relevance Score: {round(score, 4)})\n"
        )

    return result

In [123]:
tools = [
    search_and_summarize,
    extract_keywords
]

In [124]:
agent = create_agent(
    model=llm,
    tools=tools
)

In [125]:
print(tools)

[StructuredTool(name='search_and_summarize', description='Search research papers from the FAISS database,\nretrieve the top-k most similar papers,\nsummarize each paper using BART,\nand return the results as structured data.', args_schema=<class 'langchain_core.utils.pydantic.search_and_summarize'>, func=<function search_and_summarize at 0x7d036cb7fc40>), StructuredTool(name='extract_keywords', description='Extract the most important keywords from the given text\nusing the KeyBERT model.', args_schema=<class 'langchain_core.utils.pydantic.extract_keywords'>, func=<function extract_keywords at 0x7d036cb10040>)]

In [143]:
response = agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": "Extract the top 5 keywords from Deep Learning for Medical Image Reconstruction."
            }
        ]
    }
)

KeyboardInterrupt:

In [127]:
response = extract_keywords.invoke(
    {
        "text": "Deep Learning for Medical Image Reconstruction",
        "top_n": 5
    }
)

print(response)

Top Keywords:

1. image reconstruction (Relevance Score: 0.5655)
2. deep learning (Relevance Score: 0.526)
3. medical image (Relevance Score: 0.4839)
4. learning medical (Relevance Score: 0.4024)
5. reconstruction (Relevance Score: 0.3745)

In [128]:
user_query = "Extract the top 5 keywords from Deep Learning for Medical Image Reconstruction."

llm_with_tools = llm.bind_tools(tools)

response = llm_with_tools.invoke(user_query)

print(response)



print(response.tool_calls)




tool_call = response.tool_calls[0]

print(tool_call)

content='' additional_kwargs={'tool_calls': [{'id': '260q5d9e1', 'function': {'arguments': '{"text":"Deep Learning for Medical Image Reconstruction","top_n":5}', 'name': 'extract_keywords'}, 'type': 'function'}]} response_metadata={'token_usage': {'completion_tokens': 26, 'prompt_tokens': 379, 'total_tokens': 405, 'completion_time': 0.035860122, 'completion_tokens_details': None, 'prompt_time': 0.033305485, 'prompt_tokens_details': None, 'queue_time': 0.006131169, 'total_time': 0.069165607}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_020e283281', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'} id='lc_run--019f78c0-c109-76f1-82eb-7dd7d22e881e-0' tool_calls=[{'name': 'extract_keywords', 'args': {'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}, 'id': '260q5d9e1', 'type': 'tool_call'}] invalid_tool_calls=[] usage_metadata={'input_tokens': 379, 'output_tokens': 26, 'total_tokens': 405}
[{'name': 'extract_keywords', 'args': {'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}, 'id': '260q5d9e1', 'type': 'tool_call'}]
{'name': 'extract_keywords', 'args': {'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}, 'id': '260q5d9e1', 'type': 'tool_call'}

In [129]:
tool_name = tool_call["name"]

print(tool_name)

extract_keywords

In [130]:
tool_args = tool_call["args"]

print(tool_args)

{'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}

In [131]:
if tool_name == "extract_keywords":

    tool_result = extract_keywords.invoke(tool_args)

elif tool_name == "search_and_summarize":

    tool_result = search_and_summarize.invoke(tool_args)

print(tool_result)

Top Keywords:

1. image reconstruction (Relevance Score: 0.5655)
2. deep learning (Relevance Score: 0.526)
3. medical image (Relevance Score: 0.4839)
4. learning medical (Relevance Score: 0.4024)
5. reconstruction (Relevance Score: 0.3745)

In [132]:
from langchain_core.messages import ToolMessage

In [133]:
tool_message = ToolMessage(
    content=tool_result,
    tool_call_id=tool_call["id"]
)

In [134]:
print(tool_message)

content='Top Keywords:\n\n1. image reconstruction (Relevance Score: 0.5655)\n2. deep learning (Relevance Score: 0.526)\n3. medical image (Relevance Score: 0.4839)\n4. learning medical (Relevance Score: 0.4024)\n5. reconstruction (Relevance Score: 0.3745)\n' tool_call_id='260q5d9e1'

In [135]:
from langchain_core.messages import SystemMessage, HumanMessage

final_response = llm.invoke(
    [
        SystemMessage(
            content="""
You are a helpful AI assistant.

Rules:
1. Always use the tool output.
2. Never ignore tool results.
3. Present the complete tool output.
4. Add a short explanation after the tool output if necessary.
"""
        ),

        HumanMessage(content=user_query),

        response,

        tool_message
    ]
)

print(final_response.content)

The top 5 keywords extracted from the given text are related to the field of medical image reconstruction using deep learning techniques. These keywords can be useful for search engine optimization (SEO), topic modeling, or information retrieval tasks.

In [136]:
from langchain_core.messages import (
    SystemMessage,
    HumanMessage
)

final_response = llm.invoke(
[
SystemMessage(
content="""
You are a research assistant.

IMPORTANT RULES

1. Never ignore tool output.

2. Always display every keyword returned by the tool.

3. Do not summarize the keywords.

4. Print the keywords exactly as received.

5. After printing them, give a short explanation.
"""
),

HumanMessage(content=user_query),

response,

tool_message

]
)

print(final_response.content)

Explanation: The top 5 keywords extracted from the given topic are related to the application of deep learning techniques in medical image reconstruction. These keywords highlight the importance of using deep learning algorithms to improve the quality and accuracy of medical images, which is a crucial aspect of medical imaging.

In [137]:
from langchain_core.tools import tool

@tool
def compare_papers(
    paper1: str,
    paper2: str
) -> str:
    """
    Compare two research papers based on their abstracts.
    The tool retrieves the closest matching papers from the FAISS database
    and uses the LLM to compare them.
    """


    embedding1 = model.encode([paper1])

    faiss.normalize_L2(embedding1)

    D1, I1 = index.search(embedding1, 1)

    first_paper = df.iloc[I1[0][0]]


    embedding2 = model.encode([paper2])

    faiss.normalize_L2(embedding2)

    D2, I2 = index.search(embedding2, 1)

    second_paper = df.iloc[I2[0][0]]


    comparison_prompt = f"""
Compare the following two research papers.

Paper 1

Title:
{first_paper['title']}

Abstract:
{first_paper['abstract']}


Paper 2

Title:
{second_paper['title']}

Abstract:
{second_paper['abstract']}


Compare them based on:

1. Research Objective

2. Methodology

3. Key Contributions

4. Advantages

5. Limitations

6. Applications

Present the comparison in a clear table.
"""


    response = llm.invoke(comparison_prompt)

    return response.content

In [139]:
# Define a function to extract keywords from a text and return a formatted string
def get_keywords_for_text(text, top_n=5):
    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 2),
        stop_words="english",
        top_n=top_n
    )

    formatted_keywords = []
    for keyword, score in keywords:
        formatted_keywords.append(f"{keyword} (score: {score:.2f})")
    return "; ".join(formatted_keywords)

print("Keyword extraction helper function defined.")

Keyword extraction helper function defined.

In [140]:
# Select a sample of 100 papers for batch processing
sample_df = df.head(100).copy()

# Apply the keyword extraction function to the 'paper_text' column
sample_df['extracted_keywords'] = sample_df['paper_text'].apply(get_keywords_for_text)

print(f"Keywords extracted for {len(sample_df)} sample papers.")

Keywords extracted for 100 sample papers.

In [141]:
# Display the title and extracted keywords for the first 5 sampled papers
for i in range(5):
    print(f"\nPaper Title: {sample_df.iloc[i]['title']}")
    print(f"Extracted Keywords: {sample_df.iloc[i]['extracted_keywords']}")

Paper Title: Learning from compressed observations
Extracted Keywords: learning compressed (score: 0.55); information theoretic (score: 0.49); compressed observations (score: 0.46); admissible predictors (score: 0.44); achievable predictor (score: 0.43)

Paper Title: Sensor Networks with Random Links: Topology Design for Distributed
  Consensus
Extracted Keywords: consensus network (score: 0.52); distributed consensus (score: 0.52); reliable communication (score: 0.49); consensus sensor (score: 0.49); random network (score: 0.49)

Paper Title: The on-line shortest path problem under partial monitoring
Extracted Keywords: bandit problem (score: 0.58); bandit setting (score: 0.48); informed weights (score: 0.48); bandit (score: 0.48); path weights (score: 0.47)

Paper Title: A neural network approach to ordinal regression
Extracted Keywords: ordinal regression (score: 0.53); regression ordinal (score: 0.52); learn ordinal (score: 0.50); ranking bioinformatics (score: 0.48); classification regression (score: 0.45)

Paper Title: Parametric Learning and Monte Carlo Optimization
Extracted Keywords: carlo optimization (score: 0.52); parametric learning (score: 0.50); optimization parametrized (score: 0.45); learning monte (score: 0.44); blackbox optimization (score: 0.44)